version: '3.8'

services:
  app:
    image: 381491887371.dkr.ecr.ap-northeast-2.amazonaws.com/fight_repository:latest
    container_name: app_container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - redis


  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379 --appendonly yes
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
