spring:
  config:
    import:
      - classpath:/yml/application-secret.yml
    active:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${local-db.url}
    username: ${local-db.username}
    password: ${local-db.password}

  redis:
    host: ${local-redis.host}
    port: ${local-redis.port}
    password: ${local-redis.password}

  jwt:
    secret: ${jwt.secret.key.access}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 301559060384-46orh71vnndjglee64ducqcufs2ti88n.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email

          kakao:
            client-id: 8d03f285bc0b4c9ea28b6d22db28aed8
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email

          naver:
            client-id: gWAJrOF0sJXNudpBb8F8
            client-secret: EFg0KMmrsV
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response



logging:
  level:
    org.springframework.data.redis: DEBUG

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  paths-to-match:
    - /**
