local-db:
  url: jdbc:mysql://localhost:3306/fridgeTown
  username: root
  password : znzlznzl

local-redis:
  host: localhost
  port: 6379
  password: znzlznzl

jwt:
  secret:
    key:
      access: 1f6uN2mG8Q23eGnhx2hRvt2nKmPr6RNDm2vQbN5x4qE=
