local-db:
  url: jdbc:mysql://localhost:3306/aper
  username: root
  password : znzlznzl

local-redis:
  host: localhost
  port: 6379
  password: znzlznzl

jwt:
  secret:
    key:
      access: c2VjcmV0LWFjY2Vzcy1rZXktMTIz
