spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update

  config:
    import:
      - classpath:/yml/application-secret.yml
      - classpath:/yml/oauth2-dev.yml
    active:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dev-db.url}
    username: ${dev-db.username}
    password: ${dev-db.password}

  data:
    redis:
      host: ${local-redis.host}
      port: ${local-redis.port}
      password: ${local-redis.password}

  jwt:
    secret: ${jwt.secret.key.access}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1004439305409-to67cvquiebr9u797hbducdrcbl5mos0.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://3.34.46.87/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email

          kakao:
            client-id: 8d03f285bc0b4c9ea28b6d22db28aed8
            redirect-uri: "http://3.34.46.87/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email

          naver:
            client-id: VIpBl21dBFbBG6eyLfuN
            client-secret: WgZzcgFJx_
            redirect-uri: "http://3.34.46.87/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /**

