spring:
  config:
    import:
      - classpath:/yml/application-secret.yml
    active:
      on-profile: local



  data:
    redis:
      host: ${local-redis.host}
      port: ${local-redis.port}
      password: ${local-redis.password}5