spring:
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import:
      - classpath:/yml/application-secret.yml
      - classpath:/yml/oauth2-local.yml
    active:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${local-db.url}
    username: ${local-db.username}
    password: ${local-db.password}

  data:
    redis:
      host: ${local-redis.host}
      port: ${local-redis.port}
      password: ${local-redis.password}

  jwt:
    secret: ${jwt.secret.key.access}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  paths-to-match:
    - /**
