local-db:
  url: jdbc:mysql://localhost:3306/fightClub
  username: root
  password: znzlznzl

dev-db:
  url: jdbc:mysql://fight-database.cv8yqwmeqn3b.ap-northeast-2.rds.amazonaws.com
  username: admin
  password: znzlznzl

local-redis:
  host: localhost
  port: 6379
  password: znzlznzl

dev-redis:
  host: redis_container
  port: 6379
  password: znzlznzl

jwt:
  secret:
    key:
      access: e9ce8b535c44fcd074f33c4374944629fff941583ff05f37595ff59299fb3009ae64218f610add87bd3faabdc6b6a9adde8c218f0fd42c7a6ef685f4f5495153
